### ISSUE TITLE
execute problem with qoute

### ISSUE THREAD

**Issue by hadi2f244** [kkar/VBS-Obfuscator-in-Python#1]
Hi
This is a nice script ,
but i have two problems with this code !!!
1.
There is an error when the execute method runs command that contains qoutes .
for example : 
    stringa="response.Write 'hi' "
    ExEcuTe(stringa)
error : 
    Microsoft VBScript runtime error '800a01c2'
    Wrong number of arguments or invalid property assignment: 'response.Write' 
2. 
How can i use these script for asp codes?!
thank you

**Comment by kkar** [comment]
Hello!
1. This is why the script takes the characters one-by-one and turns them in to CHR(), to avoid these kind of execution problems. Try to use it with chr() values instead of double-quoes. The double-quote chr value is chr(34).
2. Not sure if ASP has the ability to Execute().
