### ISSUE TITLE
Not able to do with small vbs script

### ISSUE THREAD

**Issue by ashishsingh409** [kkar/VBS-Obfuscator-in-Python#2]
Hi, 
Not able to convert the given script:
Vbs Script:

i=10
j=10
If i=10 Then
msgbox("This is my first script,Click OK to close")
Else
msgbox("Hello world")
End if
If j=10 Then
msgbox("Hello world")
End if

displaying Error:

Obfuscator.py", line 8
    if len(sys.argv) <> 7s:
                      ^
SyntaxError: invalid syntax

**Comment by ashishsingh409** [comment]
Expecting a quick response on same.

Thanks,
Ashish Kumar

**Comment by ashishsingh409** [comment]
Thanks for your support and suggetion in advance.

Thanks,
Ashish Kumar

**Comment by kkar** [comment]
Tried to reproduce your problem with no success. Check your syntax, which has to be: python OBFUSCATOR.PY YOUR_VBS.VBS RESULT_OBFUSCATED.VBS
