### ISSUE TITLE
eval and execute: sub or function not defined

### ISSUE THREAD

**Issue by ankushgoel27** [kkar/VBS-Obfuscator-in-Python#3]
Hi,

When i try to compile the code produced by obfuscator.py in excel 2010 and word 2010, i get error on the eval and execute functions stating : " function or sub not defined". Can you please help me with this error?

**Comment by kkar** [comment]
VBS != VBA.

Office macros aren't VBS. They're VBA. Different syntax and missing functions is what you should expect.
