### ISSUE TITLE
Is this still FUD?

### ISSUE THREAD

**Issue by danthegoodman1** [kkar/VBS-Obfuscator-in-Python#4]
For word documents and excel sheets, is this still FUD on both Mac and PC? In addition to that, can the ranges be changed to allow for more/less obfuscation and hopefully making it closer to FUD? Thanks!

**Comment by kkar** [comment]
For Microsoft Office Documents you need to write code in VBA, not VBS. The same rules of obfuscation can be applied but you need to change the coding style to match with VBA's syntax. Yes, you can change the ranges to whatever you want to.
